CREATE DATABASE SENAI_SP_MEDICAL
GO

USE SENAI_SP_MEDICAL
GO

CREATE TABLE CLINICA(
	idClinica SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeClinica VARCHAR(40) UNIQUE NOT NULL,
	endereco VARCHAR(120) NOT NULL,
	cnpj VARCHAR(20) UNIQUE NOT NULL,
	razaoSocial VARCHAR(200) NOT NULL

);
GO

CREATE TABLE ESPECIALIDADE (
	idEspecialidade SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeEspecialidade VARCHAR (100) NOT NULL UNIQUE
);
GO

CREATE TABLE SITUACAO (
	idSituacao SMALLINT PRIMARY KEY IDENTITY,
	nomeSituacao VARCHAR (60) NOT NULL UNIQUE

);
GO

CREATE TABLE TIPO_USUARIO(
 idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
 nomeTipoUser VARCHAR(50) NOT NULL 

);
GO

CREATE TABLE USUARIO
(
	idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
	nomeUsuario VARCHAR(40) NOT NULL,
	email VARCHAR(50) UNIQUE NOT NULL,
	senha VARCHAR(20) NOT NULL

);
GO

CREATE TABLE MEDICO
(
	idMedico SMALLINT PRIMARY KEY IDENTITY (1,1),
	idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
	idClinica SMALLINT FOREIGN KEY REFERENCES clinica(idClinica),
	idEspecialidade SMALLINT FOREIGN KEY REFERENCES especialidade(idEspecialidade),
	crm VARCHAR(10) UNIQUE NOT NULL

);
GO

CREATE TABLE PACIENTE
(
	idPaciente SMALLINT PRIMARY KEY IDENTITY (1,1),
	idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
	dataNascimento DATE NOT NULL,
	telefone VARCHAR(12),
	rg CHAR(9) UNIQUE NOT NULL,
	cpf CHAR(11) UNIQUE NOT NULL,
	enderecoPaciente VARCHAR(120) NOT NULL

);
GO

CREATE TABLE CONSULTA(
	idConsulta SMALLINT PRIMARY KEY IDENTITY,
	idSituacao SMALLINT FOREIGN KEY REFERENCES SITUACAO (idSituacao),
	idPaciente SMALLINT FOREIGN KEY REFERENCES PACIENTE (idPaciente),
	idMedico SMALLINT FOREIGN KEY REFERENCES MEDICO (idMedico),
	dataConsulta DATETIME NOT NULL,
	descricao VARCHAR(300)

);
GO

CREATE TABLE FOTO_PERFIL (
	idFotoPerfil SMALLINT PRIMARY KEY IDENTITY,
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	nomeArquivo VARCHAR(200) UNIQUE 
);
GO
