USE SENAI_SP_MEDICAL
GO

SELECT * FROM TIPO_USUARIO
SELECT * FROM USUARIO
SELECT * FROM CLINICA
SELECT * FROM ESPECIALIDADE
SELECT * FROM SITUACAO
SELECT * FROM PACIENTE
SELECT * FROM MEDICO
SELECT * FROM CONSULTA


SELECT idConsulta, nomePaciente, nomeMedico, descricao, nomeSituacao, dataConsulta FROM CONSULTA
INNER JOIN PACIENTE
ON CONSULTA.idPaciente = PACIENTE.idPaciente
INNER JOIN MEDICO
ON CONSULTA.idMedico = MEDICO.idMedico
INNER JOIN SITUACAO
ON CONSULTA.idSituacao = SITUACAO.idSituacao